### ISSUE TITLE
Download Form is down 1/25/2017 2:26 PM

### ISSUE THREAD

**Issue by aazaff** [paleobiodb/PBDB_changelog#9] opened 2017-01-25 20:27 UTC
The download form and login are down, 502 error.

**Comment by jpjenk** [comment] 2017-01-25 20:34
Fixed with reboot of both REST and app server at 20:30 UTC on 1/25/2017. The cause should be investigated, this has happened twice since original deployment. Will begin by looking into logs.

**Comment by aazaff** [comment] 2017-01-25 20:46
@jpjenk Just for future reference, did you learn about this problem through this issue or through another means?

**Comment by jpjenk** [comment] 2017-01-25 21:13
Good point, we should have discussed this at the meeting on 1/24 (yesterday). I learned of it through GitHub email when you raised the issue because I'm watching the ChangeLog repo. It worked in this case and thank you very much for alerting me @aazaff but this is probably not the best venue for something that is clearly a server fault. Best policy would be to email me directly (jjenki25 [at] gmu.edu) and cc Michael (mmcclenn [at] geology.wisc.edu). Chances are I will receive the message first and if it really is a system administrator issue, resolve it. I'll follow up with Michael if necessary.

**Comment by aazaff** [comment] 2017-01-25 21:16
I was actually more curious if we had some sort of automated diagnostic that periodically checks for 500 series errors. I only learned about the problem because I was telegrammed by a random user.

Also, it is down again.

**Comment by jpjenk** [comment] 2017-01-25 21:25
No we don't and yes we should have a automated way of being notified about such things. I will set something up in the very near future.

I've restarted the server process so the system is operational again. I can see what the fault is and will work on a solution, keeping it alive manually until then.

I'll keep this issue open until it is properly resolved.

**Closed** 2017-03-13 23:49 UTC
